name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo build --verbose
    - run: cargo build --features=mail --verbose
    - run: cargo build --features=sentry --verbose
    - run: cargo test --verbose
